### ISSUE TITLE
problem:tensorflow.python.framework.errors_impl.InvalidArgumentError: input_2:0 is both fed and fetched.

### ISSUE THREAD

**Issue by huangd1999** [DeepImportance/deepimportance_code_release#3]
I'm trying to reproduce the experiment, but I have a problem. Can you help me?
I have install all the pkg you mention.
> python run.py
`Traceback (most recent call last):

  File "run.py", line 175, in <module>
    coverage, covered_combinations, max_comb = idc.test(X_test)
  File "/home/dong/deepimportance_code_release/coverages/idc.py", line 89, in test
    train_layer_outs = get_layer_outs_new(self.model, np.array(self.train_inputs))
  File "/home/dong/deepimportance_code_release/utils.py", line 193, in get_layer_outs_new 
return evaluater.predict(inputs)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/keras/engine/training.py", line 1167, in predict steps=steps)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop batch_outs = f(ins_batch)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__return self._call(inputs)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2635, in _call session)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2587, in _make_callablecallable_fn = session._make_callable_from_options(callable_opts)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1414, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1368, in __init__session._session, options_ptr, status)
  File "/home/dong/enter/envs/importancedriven/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__c_api.TF_GetCode(self.status.status)

tensorflow.python.framework.errors_impl.InvalidArgumentError: input_2:0 is both fed and fetched.

Exception tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidArgumentError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x7f7e41169450>> ignored
`

**Comment by gerasimou** [comment]
@huangd1999 Did you solve the problem? I suspect it probably has to do with your TensorFlow installation

**Comment by huangd1999** [comment]
> @huangd1999 Did you solve the problem? I suspect it probably has to do with your TensorFlow installation

The problem has been solved.
I change 
`    evaluater = models.Model(inputs=model.input,
                             outputs=[layer.output for index, layer in enumerate(model.layers) \
                                      if index not in skip])` 
in utils.py to 
` evaluater = models.Model(inputs=model.input,
                             outputs=[layer.output for index, layer in enumerate(model.layers) \
                                      if index not in skip][1:])`
