### ISSUE TITLE
IndexError: index 71 is out of bounds for axis 0 with size 10

### ISSUE THREAD

**Issue by huangd1999** [DeepImportance/deepimportance_code_release#5]
Hi, when I run the code `python run.py`, I have a problem, but if I change LeNet5 to LeNet1, there isn't an error.  could you help me solve that?
`Traceback (most recent call last):
 File "run.py", line 175, in <module>
   coverage, covered_combinations, max_comb = idc.test(X_test)
 File "/home/dong/deepimportance_code_release/deepimportance_code_release/coverages/idc.py", line 92, in test
   relevant_neurons)
File "/home/dong/deepimportance_code_release/deepimportance_code_release/coverages/idc.py", line 158, in quantizeSilhouette
     out_i.append(l[i])
IndexError: index 71 is out of bounds for axis 0 with size 10
`

**Comment by gerasimou** [comment]
Hi @huangd1999, I tried your command and everything seems to be working fine. Could you please check whether you have done any changes to the code? If not, would it be possible to get share a few more details of what you did?
