### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: input_2:0 is both fed and fetched

### ISSUE THREAD

**Issue by Jacob-yen** [DeepImportance/deepimportance_code_release#6]
Thank you for sharing your code!
I met an exception when I used  `python run.py` to execute the scripts. The outputs were as below:
```
Trainable layers: [1, 3, 6, 7]
Non trainable layers: [0, 2, 4, 5, 8, 9]
('Skipping layers:', [0, 5])
Loading relevance scores
('totalR loaded from ', 'experiments/LeNet5_totalR_-1_relevances.h5')
Loading unsupervised clustering results
('Could not open file: ', 'experiments/LeNet5_-1_7_2_silhouette')
Clustering results NOT FOUND; Calculating them now!
Traceback (most recent call last):
  File "run.py", line 175, in <module>
    coverage, covered_combinations, max_comb = idc.test(X_test)
  File "/data/deepimportance_code_release-master/coverages/idc.py", line 89, in test
    train_layer_outs = get_layer_outs_new(self.model, np.array(self.train_inputs))
  File "/data/deepimportance_code_release-master/utils.py", line 193, in get_layer_outs_new
    return evaluater.predict(inputs)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/keras/engine/training.py", line 1167, in predict
    steps=steps)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2635, in _call
    session)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2587, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1414, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1368, in __init__
    session._session, options_ptr, status)
  File "/root/anaconda3/envs/deepimportant_py2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: input_2:0 is both fed and fetched.
Exception tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidArgumentError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x7f98335e3410>> ignored
```
I use python `2.7` and versions of other libraries are as follows:
```
Package                       Version
----------------------------- ---------
absl-py                       0.12.0
astor                         0.8.1
backports.functools-lru-cache 1.6.1
backports.weakref             1.0.post1
certifi                       2020.6.20
cleverhans                    3.0.1
cloudpickle                   1.3.0
cycler                        0.10.0
decorator                     4.4.2
dm-tree                       0.1.5
enum34                        1.1.10
funcsigs                      1.0.2
futures                       3.3.0
gast                          0.4.0
grpcio                        1.36.1
h5py                          2.10.0
Keras                         2.2.2
Keras-Applications            1.0.4
Keras-Preprocessing           1.0.2
kiwisolver                    1.1.0
Markdown                      3.1.1
matplotlib                    2.2.5
mnist                         0.2.2
mock                          3.0.5
networkx                      2.2
nose                          1.3.7
numpy                         1.14.5
Pillow                        6.2.2
pip                           19.3.1
protobuf                      3.15.6
pycodestyle                   2.7.0
pyparsing                     2.4.7
python-dateutil               2.8.1
pytz                          2021.1
PyWavelets                    1.0.3
PyYAML                        5.4.1
scikit-image                  0.14.5
scikit-learn                  0.20.4
scipy                         1.2.3
setuptools                    39.1.0
six                           1.15.0
subprocess32                  3.5.4
tensorboard                   1.10.0
tensorflow                    1.10.0
tensorflow-probability        0.12.1
termcolor                     1.1.0
Werkzeug                      1.0.1
wheel                         0.36.2
```
Could it be an issue with the versions of the third-party libraries I installed? Or maybe I missed something in the code?
Thanks in advance and looking forward to your favorable reply.

**Comment by gerasimou** [comment]
Hi @Jacob-yen, this problem seems to occur in the get_layer_outs_new function in utils.py. It seems like a problem we encountered in the past due to using different Python version and libraries in the way that the outputs of the layers are calculated (e.g., see https://github.com/DeepImportance/deepimportance_code_release/blob/master/utils.py#L181). I will investigate it further and get back to you.

**Comment by hfeniser** [comment]
Hi @Jacob-yen, please try to uncomment line **181** in `get_layer_outs_new` function in utils.py.

**Comment by Jacob-yen** [comment]
Thank you very much. I changed the versions of python and TensorFlow (python3.7 + tensorflow1.15 + keras2.3.1) and the program seems to run successfully.
